# Generated by Django 3.1.3 on 2020-11-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='votes_toskip',
            new_name='votes_to_skip',
        ),
    ]
